id: P7EC44E70
initial_creation_type: input
source_metadata:
  title: Parāśaradharmasaṃhitā (= Parāśarasmṛti)
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Dharma -- Smṛti
  data entry: Muneo Tokunaga
  contribution to GRETIL: Muneo Tokunaga
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:29:11.608719'
last_modified_at: '2022-03-09T15:29:11.608734'
